//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ServiceGeneric.NAVWEBREF {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Mambu_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/Mambu")]
    public partial class Mambu : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RunMambuAPIOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Mambu() {
            this.Url = global::ServiceGeneric.Properties.Settings.Default.ServiceGeneric_NAVWEBREF_Mambu;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RunMambuAPICompletedEventHandler RunMambuAPICompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Mambu:RunMambuAPI", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Mambu", ResponseElementName="RunMambuAPI_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Mambu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RunMambuAPI(string docNo, decimal debAmount, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime postingDate, int transactionId, string accNo, string descriptionGJ, string typetext, string intEntry, int entNo, string gLcode, string currCode) {
            this.Invoke("RunMambuAPI", new object[] {
                        docNo,
                        debAmount,
                        postingDate,
                        transactionId,
                        accNo,
                        descriptionGJ,
                        typetext,
                        intEntry,
                        entNo,
                        gLcode,
                        currCode});
        }
        
        /// <remarks/>
        public void RunMambuAPIAsync(string docNo, decimal debAmount, System.DateTime postingDate, int transactionId, string accNo, string descriptionGJ, string typetext, string intEntry, int entNo, string gLcode, string currCode) {
            this.RunMambuAPIAsync(docNo, debAmount, postingDate, transactionId, accNo, descriptionGJ, typetext, intEntry, entNo, gLcode, currCode, null);
        }
        
        /// <remarks/>
        public void RunMambuAPIAsync(string docNo, decimal debAmount, System.DateTime postingDate, int transactionId, string accNo, string descriptionGJ, string typetext, string intEntry, int entNo, string gLcode, string currCode, object userState) {
            if ((this.RunMambuAPIOperationCompleted == null)) {
                this.RunMambuAPIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRunMambuAPIOperationCompleted);
            }
            this.InvokeAsync("RunMambuAPI", new object[] {
                        docNo,
                        debAmount,
                        postingDate,
                        transactionId,
                        accNo,
                        descriptionGJ,
                        typetext,
                        intEntry,
                        entNo,
                        gLcode,
                        currCode}, this.RunMambuAPIOperationCompleted, userState);
        }
        
        private void OnRunMambuAPIOperationCompleted(object arg) {
            if ((this.RunMambuAPICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RunMambuAPICompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void RunMambuAPICompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591